### ISSUE TITLE
Syntax error in missile.json

### ISSUE THREAD

**Issue by Epic-guy33** [MEEPofFaith/Ohno-Missiles-Mod#10]
![image](https://user-images.githubusercontent.com/59932954/72460900-a71cf800-37c5-11ea-9818-2f6aa3291489.png)

![image](https://user-images.githubusercontent.com/59932954/72460945-c451c680-37c5-11ea-92df-5a88db4f2434.png)

**Comment by MEEPofFaith** [comment]
Oh no.
What have I done.

Well. Not on my computer right now so I'll fix it later.

**Comment by SolarPH** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/59932954/72460900-a71cf800-37c5-11ea-9818-2f6aa3291489.png)
> 
> ![image](https://user-images.githubusercontent.com/59932954/72460945-c451c680-37c5-11ea-92df-5a88db4f2434.png)

It is now fixed. Meep accidentally made the "type" in both Redacted unit and Missile item to be switched to localizedName instead of name being the localizedName

As well as the statusEffects that got their name to be localizedName, which doesn't work with custom status effect.

Sumary of changes for the fix:

1. Changed localizedName to type, then name to localizedName (missile and redacted)

2. Changed localizedName to name in statusEffect (empsilo and virussilo)

I now close this issue as this issue is now solved in v2.50
